Repository book-curation/book-curation-BE, pull requests merged in 2023-03, with the labels that each got.

#53 Curation controller, service test
  src/curations/curations.controller.spec.ts
  src/curations/curations.module.ts
  src/curations/curations.service.spec.ts
  src/curations/curations.service.ts
  src/curations/dto/create-curation.dto.ts
  src/curations/dto/update-curation.dto.ts
Labels: test

#56 Create node.js.yml
  .github/workflows/curation-CI.yml
Labels: feature

#58 fix: fix to ignore git leaks for test file
  .github/workflows/curation-CI.yml
Labels: fix

#59 fix: remove git leaks from CI
  .github/workflows/curation-CI.yml
Labels: fix

#57 feat: 도커 파일 생성
  .github/workflows/curation-CD.yml
  Dockerfile
  package-lock.json
  src/hashtag/hashtag.service.spec.ts
Labels: feature

#60 Update curation-CD.yml
  .github/workflows/curation-CD.yml
Labels: fix

#62 fix: container name update
  .github/workflows/curation-CD.yml
Labels: fix

#63 dockerignore 파일 추가 - 배포 중 node_modules 에러
  .dockerignore
  package-lock.json
Labels: fix

#64 배포 파이프라인 및 Docker 파일 수정
  .github/workflows/curation-CD.yml
  Dockerfile
  package.json
Labels: fix
