Repository book-curation/book-curation-BE, pull requests merged in 2023-02, with the labels that each got.

#11 csv 파일에 있는 책 목록 DB로 bulk 업데이트
  db/migrations/1675327844139-drop-unused-column.ts
  package-lock.json
  package.json
  resources/daejeon-sample-202212.csv
  resources/insert_csv.js
  src/app.module.ts
  src/books/entity/book.entity.ts
  src/configs/typeorm.config.ts
Labels: feature

#15 Hashtag, Phase 생성 및 user, book과 관계 설정
  db/migrations/1675337138528-book-hashtag-relation.ts
  db/migrations/1675337977342-user-hashtag-relation.ts
  db/migrations/1675338340538-book-hashtag-relation.ts
  db/migrations/1675339355643-mapping-table.ts
  db/migrations/1675339709244-update-mapping-table-name.ts
  db/migrations/1675582648377-phrase-user-book-relation.ts
  package.json
  src/books/entity/book.entity.ts
  src/books/entity/hashtag.entity.ts
  src/books/entity/phrase.entity.ts
  src/users/entity/user.entity.ts
Labels: feature

#16 curation entity 생성 및 연결관계 업데이트
  db/migrations/1675081878928-create-table.ts
  db/migrations/1675327844139-drop-unused-column.ts
  db/migrations/1675337138528-book-hashtag-relation.ts
  db/migrations/1675337977342-user-hashtag-relation.ts
  db/migrations/1675338340538-book-hashtag-relation.ts
  db/migrations/1675339355643-mapping-table.ts
  db/migrations/1675339709244-update-mapping-table-name.ts
  db/migrations/1675582648377-phrase-user-book-relation.ts
  db/migrations/1675586666523-new-schema.ts
  src/books/entity/book.entity.ts
  src/books/entity/hashtag.entity.ts
  src/books/entity/phrase.entity.ts
  src/curations/entity/curation.entity.ts
  src/users/entity/user.entity.ts
Labels: feature

#22 User CRUD 작성
  db/migrations/1675682951853-update-default-date.ts
  package-lock.json
  package.json
  src/app.module.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/login.dto.ts
  src/users/dto/reset-password.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: feature

#27 api response(express 방식) 제거 -> nestjs 권장 방식으로 변경
  package-lock.json
  src/users/users.controller.ts
Labels: refactor

#28 users controller unit test
  src/books/entity/hashtag.entity.ts
  src/books/entity/phrase.entity.ts
  src/curations/entity/curation.entity.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.spec.ts
Labels: test

#29 서비스 Unit Test 완성
  package.json
  src/users/users.controller.spec.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: test

#31 eslint, prettier 적용
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/app.module.ts
  src/books/books.module.ts
  src/books/entity/book.entity.ts
  src/books/entity/hashtag.entity.ts
  src/books/entity/phrase.entity.ts
  src/curations/entity/curation.entity.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/login.dto.ts
  src/users/dto/reset-password.dto.ts
  src/users/entity/user.entity.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: feature

#34 DB 책정보 Insert 로직의 DB timeout 값 업데이트
  resources/insert_csv.js
Labels: refactor

#35 feat: Book API 생성
  src/books/books.controller.ts
  src/books/books.module.ts
  src/books/books.service.ts
Labels: feature

#37 Books controller, service test code
  src/books/books.controller.spec.ts
  src/books/books.service.spec.ts
Labels: test

#40 Phrase API - controller service module 개발
  db/migrations/1676976004987-phrase-entity-update.ts
  src/app.module.ts
  src/books/books.module.ts
  src/books/entity/book.entity.ts
  src/books/entity/phrase.entity.ts
  src/phrase/dto/create-phrase.dto.ts
  src/phrase/dto/update-phrase.dto.ts
  src/phrase/entity/phrase.entity.ts
  src/phrase/phrase.controller.spec.ts
  src/phrase/phrase.controller.ts
  src/phrase/phrase.module.ts
  src/phrase/phrase.service.spec.ts
  src/phrase/phrase.service.ts
  src/users/entity/user.entity.ts
  src/users/users.module.ts
Labels: feature

#43 Hashtag API 개발
  src/app.module.ts
  src/books/books.controller.ts
  src/books/books.module.ts
  src/books/books.service.ts
  src/books/entity/book.entity.ts
  src/hashtag/dto/create-hashtag.dto.ts
  src/hashtag/entity/hashtag.entity.ts
  src/hashtag/hashtag.controller.spec.ts
  src/hashtag/hashtag.controller.ts
  src/hashtag/hashtag.module.ts
  src/hashtag/hashtag.service.spec.ts
  src/hashtag/hashtag.service.ts
  src/users/entity/user.entity.ts
  src/users/users.service.ts
Labels: feature

#47 refactor: API 재사용성 높게 수정 및 unit test 수정
  src/books/books.module.ts
  src/books/books.service.spec.ts
  src/books/books.service.ts
  src/hashtag/hashtag.module.ts
  src/hashtag/hashtag.service.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: refactor

#48 Hashtag controller, service test 작성, book, user hashtag와 관련하여 추가 및 생성된 함수에 대한 test 작성
  src/books/books.controller.spec.ts
  src/books/books.service.spec.ts
  src/hashtag/hashtag.controller.spec.ts
  src/hashtag/hashtag.service.spec.ts
  src/hashtag/hashtag.service.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: test

#49 test: phrase unit test 작성
  src/hashtag/hashtag.service.spec.ts
  src/phrase/phrase.controller.spec.ts
  src/phrase/phrase.service.spec.ts
  src/phrase/phrase.service.ts
Labels: test

#52 Curation controller, service 생성 및 API 생성
  src/app.module.ts
  src/curations/curations.controller.spec.ts
  src/curations/curations.controller.ts
  src/curations/curations.module.ts
  src/curations/curations.service.spec.ts
  src/curations/curations.service.ts
  src/curations/dto/create-curation.dto.ts
  src/curations/dto/update-curation.dto.ts
  src/curations/entity/curation.entity.ts
Labels: feature
